### ISSUE TITLE
PPS chargers that support current control.

### ISSUE THREAD

**Issue by ysuito** [CentyLab/PicoPD#2]
I purchased this product at Elecrow. Thank you for providing a very good product.
I would like to limit the current value with setMaxCurrent(), can you tell me which PPS chargers you know that support current control?

**Comment by centydev** [comment]
You should check out UGREEN Nexode 140W. This will give you 3.3-21V 5A, max
what pps can do.

**Comment by ysuito** [comment]
Thank you for your response! I will check it out.

**Comment by centydev** [comment]
Also check this list that I have:

[UGREEN 100W Nexode Pro](https://www.amazon.com/UGREEN-Charger-Compact-MacBook-Pixelbook/dp/B0CCVQB7MY/) - PPS 3.3-21.0 @ 5A
[UGREEN 100W](https://www.amazon.com/UGREEN-100W-USB-Multiport-Charger/dp/B091Z6JNX4) - PPS 3.3 - 21.0 @ 3A
[UGREEN 140W](https://www.amazon.com/UGREEN-Charger-Nexode-Compatible-MacBook/dp/B0B129DM9T/ref=pd_lpo_sccl_1/144-3115323-5349211?pd_rd_w=uhfWx&content-id=amzn1.sym.116f529c-aa4d-4763-b2b6-4d614ec7dc00&pf_rd_p=116f529c-aa4d-4763-b2b6-4d614ec7dc00&pf_rd_r=Y7YSEXJKTEXDACENRR64&pd_rd_wg=NHqxJ&pd_rd_r=8d134cef-86d5-44e0-a1d9-f381b43e0b89&pd_rd_i=B0B129DM9T&psc=1) - PPS 3.3 - 21.0 @ 5A
[AOHI Magcube 140W](https://www.amazon.com/AOHI-Magcube-Charger-MacBook-Foldable/dp/B0C4GWH7KL/ref=sr_1_6?crid=1I81UMKXJ7MYJ&keywords=USB%2BPD%2B3.1%2Bcharger&qid=1701812867&s=electronics&sprefix=usb%2Bpd%2B3.1%2Bcharge%2Celectronics%2C152&sr=1-6&ufe=app_do%3Aamzn1.fos.17d9e15d-4e43-4581-b373-0e5c1a776d5d&th=1) - PPS 3.3 - 21.0 @ 5A
[GKUTW HX65P3 65W](https://www.amazon.com/dp/B0CJJL3WLK?th=1) - PPS 3.3 - 21 @ 3A
[Anker 737 (GaN Prime 120W)](https://www.amazon.com/Anker-Charger-GaNPrime-Compact-Foldable/dp/B09W2N774C/ref=sr_1_2?hvadid=664480320896&hvdev=c&hvlocphy=9032948&hvnetw=g&hvqmt=e&hvrand=4790283387650635545&hvtargid=kwd-1707731256195&hydadcr=3617_13689834&keywords=anker+737+charger+ganprime+120w&qid=1702342832&sr=8-2&ufe=app_do%3Aamzn1.fos.17d9e15d-4e43-4581-b373-0e5c1a776d5d) - PPS 3.3 - 11.0 @ 3A
[Anker 737 Power Bank](https://www.amazon.com/Anker-PowerCore-Portable-Charger-Compatible/dp/B09VPHVT2Z?ref_=ast_sto_dp&th=1) - PPS 3.3 - 21.0 @ 5A
[Anker PowerHouse 521](https://www.anker.com/products/a1720?variant=41982439686294) - PPS 3.3 - 11.0 @ 3A
