### ISSUE TITLE
AP33772 NRND.

### ISSUE THREAD

**Issue by mhanuel26** [CentyLab/PicoPD#3]
Hi,

I am looking at your hw design and noticed that AP33772S is recommended instead of AP33772, I need to check at differences , just wondering which IC your design uses?

Thanks for this great project.

**Comment by centydev** [comment]
Hi, this device use AP33772. At the time of development, AP33772S was not out yet. I don think you can even buy it right now. At the same time, Diodes classifies this IC as NRND after just 2 years is very odd too.
